AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - edits.gemspec
    - "tasks/**/*.rake"

Style/NumericPredicate:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
